[package]
authors = ["knoby <maximilian.brinkmann@posteo.de>"]
edition = "2018"
name = "printer_operating_box"
version = "0.1.0"

[dependencies]

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.4"
